dependencies {
    // libs
    api(rootProject.libs.bundles.baseCommons)
    api(rootProject.libs.bundles.baseJakarta)
    api(rootProject.libs.bundles.baseApacheCommons)
    api(rootProject.libs.bundles.springCore)
    api(rootProject.libs.bundles.springBootCore)
    api(rootProject.libs.bundles.http)
    api(rootProject.libs.bundles.database)
    api(rootProject.libs.bundles.json)
    api(rootProject.libs.bundles.hutool)
    api(rootProject.libs.bundles.pinyin)
    api(rootProject.libs.bundles.thymeleaf)
    api(rootProject.libs.bundles.swagger)
    compileOnly(rootProject.libs.bundles.springAiCore)
    compileOnly(rootProject.libs.bundles.springSecurityCore)
    compileOnly(rootProject.libs.bundles.mybatis)
    compileOnly(rootProject.libs.bundles.hibernate)
    compileOnly(rootProject.libs.bundles.selenium)
    compileOnly(rootProject.libs.bundles.elastic)
    compileOnly(rootProject.libs.bundles.redis)
    compileOnly(rootProject.libs.bundles.caffeine)
    compileOnly(rootProject.libs.bundles.rabbit)
    compileOnly(rootProject.libs.bundles.quartz)
    compileOnly(rootProject.libs.bundles.websocket)
    compileOnly(rootProject.libs.bundles.html)
    compileOnly(rootProject.libs.bundles.excel)
    compileOnly(rootProject.libs.bundles.pdf)
    compileOnly(rootProject.libs.bundles.image)
    compileOnly(rootProject.libs.bundles.im)
    compileOnly(rootProject.libs.bundles.ip)
    compileOnly(rootProject.libs.bundles.facebody)
    compileOnly(rootProject.libs.bundles.translate)
    compileOnly(rootProject.libs.bundles.sms)
    compileOnly(rootProject.libs.bundles.storage)
    compileOnly(rootProject.libs.bundles.telegram)
    compileOnly(rootProject.libs.bundles.quartz)
    compileOnly(rootProject.libs.bundles.sharding)
    compileOnly(rootProject.libs.bundles.office)
    compileOnly(rootProject.libs.bundles.ai)
}

tasks.named<Jar>("jar") {
    archiveBaseName.set("platform-commons-core")
}
