server:
    port: 8080
spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
        web-application-type: servlet
    application:
        name: sample-server
    profiles:
        active: local
