### --------------------------------------------------------------------------------------------------------------------
### Spring Config
### --------------------------------------------------------------------------------------------------------------------
spring:
    security:
        user:
            name: admin
            password: admin
    datasource:
        name: master
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ee_sample?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
    data:
        redis:
            host: 127.0.0.1
            port: 6379
            database: 11
            password: redis
    ai:
        model:
            chat: deepseek
        openai:
            api-key: xxx
            base-url: https://api.deepseek.com/v1/completions
        deepseek:
            api-key: xxx
        dashscope:
            api-key: xxx
### --------------------------------------------------------------------------------------------------------------------
### Platform Config
### --------------------------------------------------------------------------------------------------------------------
platform:
    cache:
        enabled: true
    data:
        core:
            enabled: true
        jpa:
            enabled: true
        mybatis:
            enabled: true
