import { Menu } from '@commons/core/utils/menu';

export const menus: Menu[] = [
    {
        key: 'workbench',
        label: 'common.label_workbench',
        icon: 'mdi:view-dashboard-outline',
        authorities: ['workbench'],
        path: '/workbench',
    },
    {
        key: 'dashboard',
        label: 'common.label_dashboard',
        icon: 'mdi:view-dashboard-outline',
        authorities: ['dashboard'],
        path: '/dashboard',
    },
    {
        key: 'home',
        label: 'common.site_management',
        icon: 'mdi:apps',
        authorities: ['site'],
        enabled: true,
        items: [
            {
                key: 'announcement-management',
                label: 'common.announcement_management',
                icon: 'mdi:bullhorn-outline',
                authorities: ['site:announcement'],
                enabled: true,
                path: '/announcement/index',
            },
            {
                key: 'poster-management',
                label: 'common.banner_management',
                icon: 'mdi:bullhorn-outline',
                authorities: ['site:poster'],
                enabled: true,
                path: '/poster/index',
            },
            {
                key: 'product-management',
                label: 'common.product_management',
                icon: 'mdi:map-outline',
                authorities: ['site:product'],
                enabled: false,
                path: '/product/index',
            },
        ],
    },
    {
        key: 'organization',
        label: 'common.organization_management',
        icon: 'mdi:account-group-outline',
        authorities: ['organization'],
        items: [
            {
                key: 'organization-organization',
                title: 'Organization',
                icon: 'mdiAccountMultiple',
                authorities: ['organization:organization'],
                enabled: false,
                path: '/organization/index',
            },
            {
                key: 'organization-position',
                title: 'Position',
                icon: 'mdiAccountMultiple',
                authorities: ['organization:position'],
                enabled: false,
                path: '/position/index',
            },
            {
                key: 'organization-user',
                label: 'common.user_management',
                icon: 'mdiAccountMultiple',
                authorities: ['organization:user'],
                enabled: true,
                path: '/user/index',
            },
            {
                key: 'organization-vip',
                label: 'common.vip_management',
                icon: 'mdiAccountMultiple',
                authorities: ['organization:user'],
                enabled: true,
                path: '/account/index',
            },
            {
                key: 'organization-group',
                title: 'Group',
                icon: 'mdiAccountMultiple',
                authorities: ['organization:group'],
                enabled: false,
                path: '/group/index',
            },
        ],
    },
    {
        key: 'resource',
        label: 'common.resource_management',
        icon: 'mdi:view-dashboard-outline',
        authorities: ['resource'],
        enabled: true,
        items: [
            {
                key: 'resource-dict',
                label: 'common.dict_management',
                icon: 'mdiAccountMultiple',
                authorities: ['resource:dict'],
                enabled: true,
                path: '/dict/index',
            },
            {
                key: 'resource-tag',
                label: '标签管理',
                icon: 'mdiAccountMultiple',
                authorities: ['resource:tag'],
                enabled: true,
                path: '/tag/index',
            },
            {
                key: 'resource:area',
                title: 'Area',
                icon: 'mdiAccountMultiple',
                authorities: ['resource:area'],
                enabled: false,
                path: '/admin/area/index',
            },
            {
                key: 'resource-attachment',
                title: 'Attachment',
                icon: 'mdiAccountMultiple',
                authorities: ['resource:attachment'],
                enabled: false,
                path: '/admin/attachment/index',
            },
            {
                key: 'resource-label',
                title: 'Label',
                icon: 'mdiAccountMultiple',
                authorities: ['resource:label'],
                enabled: false,
                path: '/admin/label/index',
            },
            {
                key: 'resource-message',
                title: 'Message',
                icon: 'mdiAccountMultiple',
                authorities: ['resource:message'],
                enabled: false,
                path: '/admin/message/index',
            },
        ],
    },
    {
        key: 'system',
        title: '系统设置',
        icon: 'mdi:cog-outline',
        authorities: ['system'],
        enabled: true,
        items: [
            {
                key: 'system-authority',
                title: 'AuthorityMiddleware',
                icon: 'mdiAccountMultiple',
                authorities: ['system:authority'],
                enabled: false,
                path: '/admin/authority/index',
            },
            {
                key: 'system-role',
                title: 'RoleModel',
                icon: 'mdiAccountMultiple',
                authorities: ['system:role'],
                enabled: false,
                path: '/admin/role/index',
            },
            {
                key: 'system-setting',
                title: 'System Settings',
                icon: 'mdiAccountMultiple',
                authorities: ['system:setting'],
                enabled: false,
                path: '/admin/system/settings',
            },
            {
                key: 'system-user',
                title: 'On-Line UserModel',
                icon: 'mdiAccountMultiple',
                authorities: ['system:user'],
                enabled: false,
                path: '/admin/on-line-user/index',
            },
            {
                key: 'system-logging',
                title: 'Logging',
                icon: 'mdiAccountMultiple',
                authorities: ['system:logging'],
                enabled: false,
                path: '/admin/logging/index',
            },
            {
                key: 'system-task',
                title: 'Task',
                icon: 'mdiAccountMultiple',
                authorities: ['system:task'],
                enabled: false,
                path: '/admin/task/index',
            },
            {
                key: 'system-application',
                title: 'ApplicationMiddleware',
                icon: 'mdiAccountMultiple',
                authorities: ['system:application'],
                enabled: false,
                path: '/admin/application/index',
            },
            {
                key: 'system-message',
                title: '消息管理',
                authorities: ['system:message'],
                enabled: true,
                path: '/message/notice/index',
            },
            {
                key: 'system-online-users',
                title: '在线用户管理',
                authorities: ['system:online-users'],
                enabled: true,
                path: '/online/users/index',
            },
        ],
    },
    {
        key: 'tenant',
        title: 'Tenant',
        icon: 'mdiSitemap',
        authorities: ['tenant'],
        enabled: false,
        items: [
            {
                key: 'tenant-tenant',
                title: 'Tenant',
                icon: 'mdiViewList',
                authorities: ['tenant:tenant'],
                enabled: false,
                path: '/admin/tenant/index',
            },
        ],
    },
];

export const userCenterMenus: Menu[] = [
    {
        key: 'user-center',
        label: 'common.user_pages_user_center_title',
        icon: 'mdi:shield-account-outline',
        path: '/user-center',
    },
    {
        key: 'user-notice',
        label: 'common.user_label_my_notice',
        icon: 'mdi:message-outline',

        path: '/user-center/notice',
    },
    {
        key: 'user-profile',
        label: 'common.user_label_my_profile',
        icon: 'mdi:information-outline',
        path: '/user-center/account',
    },
    {
        key: 'user-password',
        label: 'common.user_pages_change_password_title',
        icon: 'mdi:lock-outline',
        path: '/user-center/password',
    },
    {
        key: 'user-email',
        label: 'common.user_pages_change_email_title',
        icon: 'ant-design:mail-twotone',
        path: '/user-center/email',
    },
];
