version: "3.9"
services:
    boot-app-server:
        image: boot/boot-app-server:latest
        container_name: boot-app-server
        ports:
            - "8080:8080"
        volumes:
            - /data/app/docker/app.jar:/app/app.jar
            - /data/app/docker/app-server/logs/:/app/logs
            - /data/app/docker/app-server/config/:/app/config
        privileged: true
        network_mode: "host"
    boot-admin-server:
        image: boot/boot-admin-server:latest
        container_name: boot-admin-server
        ports:
            - "8181:8080"
        volumes:
            - /data/app/docker/admin.jar:/app/app.jar
            - /data/app/docker/admin-server/logs/:/app/logs
            - /data/app/docker/admin-server/config/:/app/config
        privileged: true
        network_mode: "host"
