version: '3.9'
services:
    ee-admin:
        image: ee:1.0
        container_name: boot-admin
        volumes:
            - /data/app/deploy/boot/admin.jar:/app/app.jar
    ee-app:
        image: ee:1.0
        container_name: boot-app
        volumes:
            - /data/app/deploy/boot/app.jar:/app/app.jar
