spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
        web-application-type: none
    application:
        name: native
    profiles:
        active: local
