### --------------------------------------------------------------------------------------------------------------------
### Spring Config
### --------------------------------------------------------------------------------------------------------------------
spring:
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            ui:
                title: Admin Console
            discovery:
                ignored-services: consul
