### --------------------------------------------------------------------------------------------------------------------
### Spring Config
### --------------------------------------------------------------------------------------------------------------------
spring:
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            context-path: /devops/sba
            ui:
                title: Admin Console
                public-url: http://ee.e.cn/devops/sba
            discovery:
                ignored-services: consul
