name: Build Native
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup Graalvm
                uses: graalvm/setup-graalvm@v1
                with:
                    distribution: "graalvm"
                    java-version: "25"
            -   name: Env
                run: |
                    echo "GRAALVM_HOME: $GRAALVM_HOME"
                    echo "JAVA_HOME: $JAVA_HOME"
                    java --version
                    native-image --version
                    gradle -v
            -   name: Build
                run: |
                    chmod a+x ./gradlew
                    ./gradlew platform-boot-server:app-server:nativeCompile

                    mkdir -p ./dist
                    cp -r ./platform-boot-server/app-server/build/native/nativeCompile/** ./dist/
                    cd ./dist
                    zip -qr native.zip *
#            -   name: Deploy
#                uses: wlixcc/SFTP-Deploy-Action@v1.2.6
#                with:
#                    server: ${{ secrets.SERVER_HOST }}
#                    username: ${{ secrets.SERVER_USER }}
#                    ssh_private_key: ${{ secrets.SERVER_KEY }}
#                    local_path: "dist/native.zip"
#                    remote_path: "/data/app/deploy"
#                    sftpArgs: "-o ConnectTimeout=5"
